FROM nvidia/cuda:12.0.0-base-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN adduser --disabled-password --gecos '' relik-user \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
    curl wget python3.10 python3-distutils python3-pip \
    && rm -rf /var/lib/apt/lists/*

USER relik-user
ENV PATH=${PATH}:/home/relik-user/.local/bin

# Set the working directory
COPY --chown=relik-user:relik-user . /home/relik-user/relik
WORKDIR /home/relik-user/relik

RUN pip install --upgrade --no-cache-dir .[serve] \
    && chmod +x scripts/docker/start-gunic.sh

EXPOSE 8000

ENTRYPOINT ["scripts/docker/start-gunic.sh"]
