FROM python:3.10.13-slim-bullseye

ARG DEBIAN_FRONTEND=noninteractive

RUN adduser --disabled-password --gecos '' relik-user
USER relik-user
ENV PATH=${PATH}:/home/relik-user/.local/bin

# Set the working directory
COPY --chown=relik-user:relik-user . /home/relik-user/relik
WORKDIR /home/relik-user/relik

RUN pip install --upgrade --no-cache-dir .[serve] -c constraints.cpu.txt \
    && chmod +x scripts/docker/start-gunic.sh

EXPOSE 8000 8001

ENTRYPOINT ["scripts/docker/start-gunic.sh"]
